/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as FunnelRouteImport } from "./routes/_funnel"
import { Route as DashboardRouteImport } from "./routes/_dashboard"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FunnelNewProjectRouteImport } from "./routes/_funnel/new-project"
import { Route as DashboardVisibilityRouteImport } from "./routes/_dashboard/visibility"
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings"
import { Route as DashboardReportsRouteImport } from "./routes/_dashboard/reports"
import { Route as DashboardProjectsRouteImport } from "./routes/_dashboard/projects"
import { Route as DashboardPlatformsRouteImport } from "./routes/_dashboard/platforms"
import { Route as DashboardOverviewRouteImport } from "./routes/_dashboard/overview"
import { Route as DashboardCompetitorsRouteImport } from "./routes/_dashboard/competitors"
import { Route as DashboardCitationsRouteImport } from "./routes/_dashboard/citations"
import { Route as DashboardAssistantRouteImport } from "./routes/_dashboard/assistant"
import { Route as AuthResetPasswordRouteImport } from "./routes/_auth/reset-password"
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password"
import { Route as AuthCompleteSignupRouteImport } from "./routes/_auth/complete-signup"
import { Route as AuthAcceptInviteRouteImport } from "./routes/_auth/accept-invite"
import { Route as SharedReportsShareTokenRouteImport } from "./routes/shared.reports.$shareToken"
import { Route as DashboardReportsReportIdRouteImport } from "./routes/_dashboard/reports.$reportId"
import { Route as DashboardProjectsNewRouteImport } from "./routes/_dashboard/projects_.new"
import { Route as DashboardProjectsProjectIdRouteImport } from "./routes/_dashboard/projects.$projectId"
import { Route as DashboardProjectsProjectIdRunsRouteImport } from "./routes/_dashboard/projects.$projectId.runs"
import { Route as DashboardProjectsProjectIdQueriesRouteImport } from "./routes/_dashboard/projects.$projectId.queries"
import { Route as DashboardProjectsProjectIdAnswersRouteImport } from "./routes/_dashboard/projects.$projectId.answers"

const FunnelRoute = FunnelRouteImport.update({
  id: "/_funnel",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelNewProjectRoute = FunnelNewProjectRouteImport.update({
  id: "/new-project",
  path: "/new-project",
  getParentRoute: () => FunnelRoute,
} as any)
const DashboardVisibilityRoute = DashboardVisibilityRouteImport.update({
  id: "/visibility",
  path: "/visibility",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformsRoute = DashboardPlatformsRouteImport.update({
  id: "/platforms",
  path: "/platforms",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: "/competitors",
  path: "/competitors",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitationsRoute = DashboardCitationsRouteImport.update({
  id: "/citations",
  path: "/citations",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: "/assistant",
  path: "/assistant",
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteSignupRoute = AuthCompleteSignupRouteImport.update({
  id: "/complete-signup",
  path: "/complete-signup",
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: "/accept-invite",
  path: "/accept-invite",
  getParentRoute: () => AuthRoute,
} as any)
const SharedReportsShareTokenRoute = SharedReportsShareTokenRouteImport.update({
  id: "/shared/reports/$shareToken",
  path: "/shared/reports/$shareToken",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsReportIdRoute =
  DashboardReportsReportIdRouteImport.update({
    id: "/$reportId",
    path: "/$reportId",
    getParentRoute: () => DashboardReportsRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: "/projects_/new",
  path: "/projects/new",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: "/$projectId",
    path: "/$projectId",
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdRunsRoute =
  DashboardProjectsProjectIdRunsRouteImport.update({
    id: "/runs",
    path: "/runs",
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdQueriesRoute =
  DashboardProjectsProjectIdQueriesRouteImport.update({
    id: "/queries",
    path: "/queries",
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdAnswersRoute =
  DashboardProjectsProjectIdAnswersRouteImport.update({
    id: "/answers",
    path: "/answers",
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/accept-invite": typeof AuthAcceptInviteRoute
  "/complete-signup": typeof AuthCompleteSignupRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/assistant": typeof DashboardAssistantRoute
  "/citations": typeof DashboardCitationsRoute
  "/competitors": typeof DashboardCompetitorsRoute
  "/overview": typeof DashboardOverviewRoute
  "/platforms": typeof DashboardPlatformsRoute
  "/projects": typeof DashboardProjectsRouteWithChildren
  "/reports": typeof DashboardReportsRouteWithChildren
  "/settings": typeof DashboardSettingsRoute
  "/visibility": typeof DashboardVisibilityRoute
  "/new-project": typeof FunnelNewProjectRoute
  "/projects/$projectId": typeof DashboardProjectsProjectIdRouteWithChildren
  "/projects/new": typeof DashboardProjectsNewRoute
  "/reports/$reportId": typeof DashboardReportsReportIdRoute
  "/shared/reports/$shareToken": typeof SharedReportsShareTokenRoute
  "/projects/$projectId/answers": typeof DashboardProjectsProjectIdAnswersRoute
  "/projects/$projectId/queries": typeof DashboardProjectsProjectIdQueriesRoute
  "/projects/$projectId/runs": typeof DashboardProjectsProjectIdRunsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/accept-invite": typeof AuthAcceptInviteRoute
  "/complete-signup": typeof AuthCompleteSignupRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/assistant": typeof DashboardAssistantRoute
  "/citations": typeof DashboardCitationsRoute
  "/competitors": typeof DashboardCompetitorsRoute
  "/overview": typeof DashboardOverviewRoute
  "/platforms": typeof DashboardPlatformsRoute
  "/projects": typeof DashboardProjectsRouteWithChildren
  "/reports": typeof DashboardReportsRouteWithChildren
  "/settings": typeof DashboardSettingsRoute
  "/visibility": typeof DashboardVisibilityRoute
  "/new-project": typeof FunnelNewProjectRoute
  "/projects/$projectId": typeof DashboardProjectsProjectIdRouteWithChildren
  "/projects/new": typeof DashboardProjectsNewRoute
  "/reports/$reportId": typeof DashboardReportsReportIdRoute
  "/shared/reports/$shareToken": typeof SharedReportsShareTokenRoute
  "/projects/$projectId/answers": typeof DashboardProjectsProjectIdAnswersRoute
  "/projects/$projectId/queries": typeof DashboardProjectsProjectIdQueriesRoute
  "/projects/$projectId/runs": typeof DashboardProjectsProjectIdRunsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/_dashboard": typeof DashboardRouteWithChildren
  "/_funnel": typeof FunnelRouteWithChildren
  "/_auth/accept-invite": typeof AuthAcceptInviteRoute
  "/_auth/complete-signup": typeof AuthCompleteSignupRoute
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/register": typeof AuthRegisterRoute
  "/_auth/reset-password": typeof AuthResetPasswordRoute
  "/_dashboard/assistant": typeof DashboardAssistantRoute
  "/_dashboard/citations": typeof DashboardCitationsRoute
  "/_dashboard/competitors": typeof DashboardCompetitorsRoute
  "/_dashboard/overview": typeof DashboardOverviewRoute
  "/_dashboard/platforms": typeof DashboardPlatformsRoute
  "/_dashboard/projects": typeof DashboardProjectsRouteWithChildren
  "/_dashboard/reports": typeof DashboardReportsRouteWithChildren
  "/_dashboard/settings": typeof DashboardSettingsRoute
  "/_dashboard/visibility": typeof DashboardVisibilityRoute
  "/_funnel/new-project": typeof FunnelNewProjectRoute
  "/_dashboard/projects/$projectId": typeof DashboardProjectsProjectIdRouteWithChildren
  "/_dashboard/projects_/new": typeof DashboardProjectsNewRoute
  "/_dashboard/reports/$reportId": typeof DashboardReportsReportIdRoute
  "/shared/reports/$shareToken": typeof SharedReportsShareTokenRoute
  "/_dashboard/projects/$projectId/answers": typeof DashboardProjectsProjectIdAnswersRoute
  "/_dashboard/projects/$projectId/queries": typeof DashboardProjectsProjectIdQueriesRoute
  "/_dashboard/projects/$projectId/runs": typeof DashboardProjectsProjectIdRunsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/accept-invite"
    | "/complete-signup"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/assistant"
    | "/citations"
    | "/competitors"
    | "/overview"
    | "/platforms"
    | "/projects"
    | "/reports"
    | "/settings"
    | "/visibility"
    | "/new-project"
    | "/projects/$projectId"
    | "/projects/new"
    | "/reports/$reportId"
    | "/shared/reports/$shareToken"
    | "/projects/$projectId/answers"
    | "/projects/$projectId/queries"
    | "/projects/$projectId/runs"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/accept-invite"
    | "/complete-signup"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/assistant"
    | "/citations"
    | "/competitors"
    | "/overview"
    | "/platforms"
    | "/projects"
    | "/reports"
    | "/settings"
    | "/visibility"
    | "/new-project"
    | "/projects/$projectId"
    | "/projects/new"
    | "/reports/$reportId"
    | "/shared/reports/$shareToken"
    | "/projects/$projectId/answers"
    | "/projects/$projectId/queries"
    | "/projects/$projectId/runs"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_dashboard"
    | "/_funnel"
    | "/_auth/accept-invite"
    | "/_auth/complete-signup"
    | "/_auth/forgot-password"
    | "/_auth/login"
    | "/_auth/register"
    | "/_auth/reset-password"
    | "/_dashboard/assistant"
    | "/_dashboard/citations"
    | "/_dashboard/competitors"
    | "/_dashboard/overview"
    | "/_dashboard/platforms"
    | "/_dashboard/projects"
    | "/_dashboard/reports"
    | "/_dashboard/settings"
    | "/_dashboard/visibility"
    | "/_funnel/new-project"
    | "/_dashboard/projects/$projectId"
    | "/_dashboard/projects_/new"
    | "/_dashboard/reports/$reportId"
    | "/shared/reports/$shareToken"
    | "/_dashboard/projects/$projectId/answers"
    | "/_dashboard/projects/$projectId/queries"
    | "/_dashboard/projects/$projectId/runs"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FunnelRoute: typeof FunnelRouteWithChildren
  SharedReportsShareTokenRoute: typeof SharedReportsShareTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_funnel": {
      id: "/_funnel"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_funnel/new-project": {
      id: "/_funnel/new-project"
      path: "/new-project"
      fullPath: "/new-project"
      preLoaderRoute: typeof FunnelNewProjectRouteImport
      parentRoute: typeof FunnelRoute
    }
    "/_dashboard/visibility": {
      id: "/_dashboard/visibility"
      path: "/visibility"
      fullPath: "/visibility"
      preLoaderRoute: typeof DashboardVisibilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/settings": {
      id: "/_dashboard/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/reports": {
      id: "/_dashboard/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects": {
      id: "/_dashboard/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/platforms": {
      id: "/_dashboard/platforms"
      path: "/platforms"
      fullPath: "/platforms"
      preLoaderRoute: typeof DashboardPlatformsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/overview": {
      id: "/_dashboard/overview"
      path: "/overview"
      fullPath: "/overview"
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/competitors": {
      id: "/_dashboard/competitors"
      path: "/competitors"
      fullPath: "/competitors"
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/citations": {
      id: "/_dashboard/citations"
      path: "/citations"
      fullPath: "/citations"
      preLoaderRoute: typeof DashboardCitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/assistant": {
      id: "/_dashboard/assistant"
      path: "/assistant"
      fullPath: "/assistant"
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_auth/reset-password": {
      id: "/_auth/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/register": {
      id: "/_auth/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/complete-signup": {
      id: "/_auth/complete-signup"
      path: "/complete-signup"
      fullPath: "/complete-signup"
      preLoaderRoute: typeof AuthCompleteSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/accept-invite": {
      id: "/_auth/accept-invite"
      path: "/accept-invite"
      fullPath: "/accept-invite"
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    "/shared/reports/$shareToken": {
      id: "/shared/reports/$shareToken"
      path: "/shared/reports/$shareToken"
      fullPath: "/shared/reports/$shareToken"
      preLoaderRoute: typeof SharedReportsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/reports/$reportId": {
      id: "/_dashboard/reports/$reportId"
      path: "/$reportId"
      fullPath: "/reports/$reportId"
      preLoaderRoute: typeof DashboardReportsReportIdRouteImport
      parentRoute: typeof DashboardReportsRoute
    }
    "/_dashboard/projects_/new": {
      id: "/_dashboard/projects_/new"
      path: "/projects/new"
      fullPath: "/projects/new"
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects/$projectId": {
      id: "/_dashboard/projects/$projectId"
      path: "/$projectId"
      fullPath: "/projects/$projectId"
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    "/_dashboard/projects/$projectId/runs": {
      id: "/_dashboard/projects/$projectId/runs"
      path: "/runs"
      fullPath: "/projects/$projectId/runs"
      preLoaderRoute: typeof DashboardProjectsProjectIdRunsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    "/_dashboard/projects/$projectId/queries": {
      id: "/_dashboard/projects/$projectId/queries"
      path: "/queries"
      fullPath: "/projects/$projectId/queries"
      preLoaderRoute: typeof DashboardProjectsProjectIdQueriesRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    "/_dashboard/projects/$projectId/answers": {
      id: "/_dashboard/projects/$projectId/answers"
      path: "/answers"
      fullPath: "/projects/$projectId/answers"
      preLoaderRoute: typeof DashboardProjectsProjectIdAnswersRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCompleteSignupRoute: typeof AuthCompleteSignupRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCompleteSignupRoute: AuthCompleteSignupRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdAnswersRoute: typeof DashboardProjectsProjectIdAnswersRoute
  DashboardProjectsProjectIdQueriesRoute: typeof DashboardProjectsProjectIdQueriesRoute
  DashboardProjectsProjectIdRunsRoute: typeof DashboardProjectsProjectIdRunsRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdAnswersRoute:
      DashboardProjectsProjectIdAnswersRoute,
    DashboardProjectsProjectIdQueriesRoute:
      DashboardProjectsProjectIdQueriesRoute,
    DashboardProjectsProjectIdRunsRoute: DashboardProjectsProjectIdRunsRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardReportsRouteChildren {
  DashboardReportsReportIdRoute: typeof DashboardReportsReportIdRoute
}

const DashboardReportsRouteChildren: DashboardReportsRouteChildren = {
  DashboardReportsReportIdRoute: DashboardReportsReportIdRoute,
}

const DashboardReportsRouteWithChildren =
  DashboardReportsRoute._addFileChildren(DashboardReportsRouteChildren)

interface DashboardRouteChildren {
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardCitationsRoute: typeof DashboardCitationsRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardPlatformsRoute: typeof DashboardPlatformsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardReportsRoute: typeof DashboardReportsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVisibilityRoute: typeof DashboardVisibilityRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardCitationsRoute: DashboardCitationsRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardPlatformsRoute: DashboardPlatformsRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardReportsRoute: DashboardReportsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVisibilityRoute: DashboardVisibilityRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FunnelRouteChildren {
  FunnelNewProjectRoute: typeof FunnelNewProjectRoute
}

const FunnelRouteChildren: FunnelRouteChildren = {
  FunnelNewProjectRoute: FunnelNewProjectRoute,
}

const FunnelRouteWithChildren =
  FunnelRoute._addFileChildren(FunnelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FunnelRoute: FunnelRouteWithChildren,
  SharedReportsShareTokenRoute: SharedReportsShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
