/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as FunnelRouteImport } from "./routes/_funnel"
import { Route as DashboardRouteImport } from "./routes/_dashboard"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as EmbedEmbedTokenRouteImport } from "./routes/embed.$embedToken"
import { Route as FunnelNewProjectRouteImport } from "./routes/_funnel/new-project"
import { Route as DashboardWidgetsRouteImport } from "./routes/_dashboard/widgets"
import { Route as DashboardVisibilityRouteImport } from "./routes/_dashboard/visibility"
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings"
import { Route as DashboardReportsRouteImport } from "./routes/_dashboard/reports"
import { Route as DashboardProjectsRouteImport } from "./routes/_dashboard/projects"
import { Route as DashboardOverviewRouteImport } from "./routes/_dashboard/overview"
import { Route as DashboardContentRouteImport } from "./routes/_dashboard/content"
import { Route as AuthResetPasswordRouteImport } from "./routes/_auth/reset-password"
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password"
import { Route as AuthCompleteSignupRouteImport } from "./routes/_auth/complete-signup"
import { Route as AuthAcceptInviteRouteImport } from "./routes/_auth/accept-invite"
import { Route as SharedReportsShareTokenRouteImport } from "./routes/shared.reports.$shareToken"
import { Route as DashboardReportsReportIdRouteImport } from "./routes/_dashboard/reports.$reportId"
import { Route as DashboardProjectsNewRouteImport } from "./routes/_dashboard/projects_.new"
import { Route as DashboardProjectsProjectIdRouteImport } from "./routes/_dashboard/projects.$projectId"
import { Route as DashboardAdminAiUsageRouteImport } from "./routes/_dashboard/admin/ai-usage"
import { Route as DashboardAdminAiKeysRouteImport } from "./routes/_dashboard/admin/ai-keys"
import { Route as DashboardProjectsProjectIdKnowledgeRouteImport } from "./routes/_dashboard/projects_.$projectId_.knowledge"
import { Route as DashboardProjectsProjectIdRunsRouteImport } from "./routes/_dashboard/projects.$projectId.runs"
import { Route as DashboardProjectsProjectIdQueriesRouteImport } from "./routes/_dashboard/projects.$projectId.queries"
import { Route as DashboardProjectsProjectIdAnswersRouteImport } from "./routes/_dashboard/projects.$projectId.answers"
import { Route as DashboardAdminAiUsageTenantIdRouteImport } from "./routes/_dashboard/admin/ai-usage.$tenantId"

const FunnelRoute = FunnelRouteImport.update({
  id: "/_funnel",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedEmbedTokenRoute = EmbedEmbedTokenRouteImport.update({
  id: "/embed/$embedToken",
  path: "/embed/$embedToken",
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelNewProjectRoute = FunnelNewProjectRouteImport.update({
  id: "/new-project",
  path: "/new-project",
  getParentRoute: () => FunnelRoute,
} as any)
const DashboardWidgetsRoute = DashboardWidgetsRouteImport.update({
  id: "/widgets",
  path: "/widgets",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVisibilityRoute = DashboardVisibilityRouteImport.update({
  id: "/visibility",
  path: "/visibility",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: "/content",
  path: "/content",
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteSignupRoute = AuthCompleteSignupRouteImport.update({
  id: "/complete-signup",
  path: "/complete-signup",
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: "/accept-invite",
  path: "/accept-invite",
  getParentRoute: () => AuthRoute,
} as any)
const SharedReportsShareTokenRoute = SharedReportsShareTokenRouteImport.update({
  id: "/shared/reports/$shareToken",
  path: "/shared/reports/$shareToken",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsReportIdRoute =
  DashboardReportsReportIdRouteImport.update({
    id: "/$reportId",
    path: "/$reportId",
    getParentRoute: () => DashboardReportsRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: "/projects_/new",
  path: "/projects/new",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: "/$projectId",
    path: "/$projectId",
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardAdminAiUsageRoute = DashboardAdminAiUsageRouteImport.update({
  id: "/admin/ai-usage",
  path: "/admin/ai-usage",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAiKeysRoute = DashboardAdminAiKeysRouteImport.update({
  id: "/admin/ai-keys",
  path: "/admin/ai-keys",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdKnowledgeRoute =
  DashboardProjectsProjectIdKnowledgeRouteImport.update({
    id: "/projects_/$projectId_/knowledge",
    path: "/projects/$projectId/knowledge",
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdRunsRoute =
  DashboardProjectsProjectIdRunsRouteImport.update({
    id: "/runs",
    path: "/runs",
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdQueriesRoute =
  DashboardProjectsProjectIdQueriesRouteImport.update({
    id: "/queries",
    path: "/queries",
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdAnswersRoute =
  DashboardProjectsProjectIdAnswersRouteImport.update({
    id: "/answers",
    path: "/answers",
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardAdminAiUsageTenantIdRoute =
  DashboardAdminAiUsageTenantIdRouteImport.update({
    id: "/$tenantId",
    path: "/$tenantId",
    getParentRoute: () => DashboardAdminAiUsageRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/accept-invite": typeof AuthAcceptInviteRoute
  "/complete-signup": typeof AuthCompleteSignupRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/content": typeof DashboardContentRoute
  "/overview": typeof DashboardOverviewRoute
  "/projects": typeof DashboardProjectsRouteWithChildren
  "/reports": typeof DashboardReportsRouteWithChildren
  "/settings": typeof DashboardSettingsRoute
  "/visibility": typeof DashboardVisibilityRoute
  "/widgets": typeof DashboardWidgetsRoute
  "/new-project": typeof FunnelNewProjectRoute
  "/embed/$embedToken": typeof EmbedEmbedTokenRoute
  "/admin/ai-keys": typeof DashboardAdminAiKeysRoute
  "/admin/ai-usage": typeof DashboardAdminAiUsageRouteWithChildren
  "/projects/$projectId": typeof DashboardProjectsProjectIdRouteWithChildren
  "/projects/new": typeof DashboardProjectsNewRoute
  "/reports/$reportId": typeof DashboardReportsReportIdRoute
  "/shared/reports/$shareToken": typeof SharedReportsShareTokenRoute
  "/admin/ai-usage/$tenantId": typeof DashboardAdminAiUsageTenantIdRoute
  "/projects/$projectId/answers": typeof DashboardProjectsProjectIdAnswersRoute
  "/projects/$projectId/queries": typeof DashboardProjectsProjectIdQueriesRoute
  "/projects/$projectId/runs": typeof DashboardProjectsProjectIdRunsRoute
  "/projects/$projectId/knowledge": typeof DashboardProjectsProjectIdKnowledgeRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/accept-invite": typeof AuthAcceptInviteRoute
  "/complete-signup": typeof AuthCompleteSignupRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/reset-password": typeof AuthResetPasswordRoute
  "/content": typeof DashboardContentRoute
  "/overview": typeof DashboardOverviewRoute
  "/projects": typeof DashboardProjectsRouteWithChildren
  "/reports": typeof DashboardReportsRouteWithChildren
  "/settings": typeof DashboardSettingsRoute
  "/visibility": typeof DashboardVisibilityRoute
  "/widgets": typeof DashboardWidgetsRoute
  "/new-project": typeof FunnelNewProjectRoute
  "/embed/$embedToken": typeof EmbedEmbedTokenRoute
  "/admin/ai-keys": typeof DashboardAdminAiKeysRoute
  "/admin/ai-usage": typeof DashboardAdminAiUsageRouteWithChildren
  "/projects/$projectId": typeof DashboardProjectsProjectIdRouteWithChildren
  "/projects/new": typeof DashboardProjectsNewRoute
  "/reports/$reportId": typeof DashboardReportsReportIdRoute
  "/shared/reports/$shareToken": typeof SharedReportsShareTokenRoute
  "/admin/ai-usage/$tenantId": typeof DashboardAdminAiUsageTenantIdRoute
  "/projects/$projectId/answers": typeof DashboardProjectsProjectIdAnswersRoute
  "/projects/$projectId/queries": typeof DashboardProjectsProjectIdQueriesRoute
  "/projects/$projectId/runs": typeof DashboardProjectsProjectIdRunsRoute
  "/projects/$projectId/knowledge": typeof DashboardProjectsProjectIdKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/_dashboard": typeof DashboardRouteWithChildren
  "/_funnel": typeof FunnelRouteWithChildren
  "/_auth/accept-invite": typeof AuthAcceptInviteRoute
  "/_auth/complete-signup": typeof AuthCompleteSignupRoute
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/register": typeof AuthRegisterRoute
  "/_auth/reset-password": typeof AuthResetPasswordRoute
  "/_dashboard/content": typeof DashboardContentRoute
  "/_dashboard/overview": typeof DashboardOverviewRoute
  "/_dashboard/projects": typeof DashboardProjectsRouteWithChildren
  "/_dashboard/reports": typeof DashboardReportsRouteWithChildren
  "/_dashboard/settings": typeof DashboardSettingsRoute
  "/_dashboard/visibility": typeof DashboardVisibilityRoute
  "/_dashboard/widgets": typeof DashboardWidgetsRoute
  "/_funnel/new-project": typeof FunnelNewProjectRoute
  "/embed/$embedToken": typeof EmbedEmbedTokenRoute
  "/_dashboard/admin/ai-keys": typeof DashboardAdminAiKeysRoute
  "/_dashboard/admin/ai-usage": typeof DashboardAdminAiUsageRouteWithChildren
  "/_dashboard/projects/$projectId": typeof DashboardProjectsProjectIdRouteWithChildren
  "/_dashboard/projects_/new": typeof DashboardProjectsNewRoute
  "/_dashboard/reports/$reportId": typeof DashboardReportsReportIdRoute
  "/shared/reports/$shareToken": typeof SharedReportsShareTokenRoute
  "/_dashboard/admin/ai-usage/$tenantId": typeof DashboardAdminAiUsageTenantIdRoute
  "/_dashboard/projects/$projectId/answers": typeof DashboardProjectsProjectIdAnswersRoute
  "/_dashboard/projects/$projectId/queries": typeof DashboardProjectsProjectIdQueriesRoute
  "/_dashboard/projects/$projectId/runs": typeof DashboardProjectsProjectIdRunsRoute
  "/_dashboard/projects_/$projectId_/knowledge": typeof DashboardProjectsProjectIdKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/accept-invite"
    | "/complete-signup"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/content"
    | "/overview"
    | "/projects"
    | "/reports"
    | "/settings"
    | "/visibility"
    | "/widgets"
    | "/new-project"
    | "/embed/$embedToken"
    | "/admin/ai-keys"
    | "/admin/ai-usage"
    | "/projects/$projectId"
    | "/projects/new"
    | "/reports/$reportId"
    | "/shared/reports/$shareToken"
    | "/admin/ai-usage/$tenantId"
    | "/projects/$projectId/answers"
    | "/projects/$projectId/queries"
    | "/projects/$projectId/runs"
    | "/projects/$projectId/knowledge"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/accept-invite"
    | "/complete-signup"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/content"
    | "/overview"
    | "/projects"
    | "/reports"
    | "/settings"
    | "/visibility"
    | "/widgets"
    | "/new-project"
    | "/embed/$embedToken"
    | "/admin/ai-keys"
    | "/admin/ai-usage"
    | "/projects/$projectId"
    | "/projects/new"
    | "/reports/$reportId"
    | "/shared/reports/$shareToken"
    | "/admin/ai-usage/$tenantId"
    | "/projects/$projectId/answers"
    | "/projects/$projectId/queries"
    | "/projects/$projectId/runs"
    | "/projects/$projectId/knowledge"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_dashboard"
    | "/_funnel"
    | "/_auth/accept-invite"
    | "/_auth/complete-signup"
    | "/_auth/forgot-password"
    | "/_auth/login"
    | "/_auth/register"
    | "/_auth/reset-password"
    | "/_dashboard/content"
    | "/_dashboard/overview"
    | "/_dashboard/projects"
    | "/_dashboard/reports"
    | "/_dashboard/settings"
    | "/_dashboard/visibility"
    | "/_dashboard/widgets"
    | "/_funnel/new-project"
    | "/embed/$embedToken"
    | "/_dashboard/admin/ai-keys"
    | "/_dashboard/admin/ai-usage"
    | "/_dashboard/projects/$projectId"
    | "/_dashboard/projects_/new"
    | "/_dashboard/reports/$reportId"
    | "/shared/reports/$shareToken"
    | "/_dashboard/admin/ai-usage/$tenantId"
    | "/_dashboard/projects/$projectId/answers"
    | "/_dashboard/projects/$projectId/queries"
    | "/_dashboard/projects/$projectId/runs"
    | "/_dashboard/projects_/$projectId_/knowledge"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FunnelRoute: typeof FunnelRouteWithChildren
  EmbedEmbedTokenRoute: typeof EmbedEmbedTokenRoute
  SharedReportsShareTokenRoute: typeof SharedReportsShareTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_funnel": {
      id: "/_funnel"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/embed/$embedToken": {
      id: "/embed/$embedToken"
      path: "/embed/$embedToken"
      fullPath: "/embed/$embedToken"
      preLoaderRoute: typeof EmbedEmbedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_funnel/new-project": {
      id: "/_funnel/new-project"
      path: "/new-project"
      fullPath: "/new-project"
      preLoaderRoute: typeof FunnelNewProjectRouteImport
      parentRoute: typeof FunnelRoute
    }
    "/_dashboard/widgets": {
      id: "/_dashboard/widgets"
      path: "/widgets"
      fullPath: "/widgets"
      preLoaderRoute: typeof DashboardWidgetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/visibility": {
      id: "/_dashboard/visibility"
      path: "/visibility"
      fullPath: "/visibility"
      preLoaderRoute: typeof DashboardVisibilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/settings": {
      id: "/_dashboard/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/reports": {
      id: "/_dashboard/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects": {
      id: "/_dashboard/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/overview": {
      id: "/_dashboard/overview"
      path: "/overview"
      fullPath: "/overview"
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/content": {
      id: "/_dashboard/content"
      path: "/content"
      fullPath: "/content"
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_auth/reset-password": {
      id: "/_auth/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/register": {
      id: "/_auth/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/complete-signup": {
      id: "/_auth/complete-signup"
      path: "/complete-signup"
      fullPath: "/complete-signup"
      preLoaderRoute: typeof AuthCompleteSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/accept-invite": {
      id: "/_auth/accept-invite"
      path: "/accept-invite"
      fullPath: "/accept-invite"
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    "/shared/reports/$shareToken": {
      id: "/shared/reports/$shareToken"
      path: "/shared/reports/$shareToken"
      fullPath: "/shared/reports/$shareToken"
      preLoaderRoute: typeof SharedReportsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/reports/$reportId": {
      id: "/_dashboard/reports/$reportId"
      path: "/$reportId"
      fullPath: "/reports/$reportId"
      preLoaderRoute: typeof DashboardReportsReportIdRouteImport
      parentRoute: typeof DashboardReportsRoute
    }
    "/_dashboard/projects_/new": {
      id: "/_dashboard/projects_/new"
      path: "/projects/new"
      fullPath: "/projects/new"
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects/$projectId": {
      id: "/_dashboard/projects/$projectId"
      path: "/$projectId"
      fullPath: "/projects/$projectId"
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    "/_dashboard/admin/ai-usage": {
      id: "/_dashboard/admin/ai-usage"
      path: "/admin/ai-usage"
      fullPath: "/admin/ai-usage"
      preLoaderRoute: typeof DashboardAdminAiUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/admin/ai-keys": {
      id: "/_dashboard/admin/ai-keys"
      path: "/admin/ai-keys"
      fullPath: "/admin/ai-keys"
      preLoaderRoute: typeof DashboardAdminAiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects_/$projectId_/knowledge": {
      id: "/_dashboard/projects_/$projectId_/knowledge"
      path: "/projects/$projectId/knowledge"
      fullPath: "/projects/$projectId/knowledge"
      preLoaderRoute: typeof DashboardProjectsProjectIdKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects/$projectId/runs": {
      id: "/_dashboard/projects/$projectId/runs"
      path: "/runs"
      fullPath: "/projects/$projectId/runs"
      preLoaderRoute: typeof DashboardProjectsProjectIdRunsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    "/_dashboard/projects/$projectId/queries": {
      id: "/_dashboard/projects/$projectId/queries"
      path: "/queries"
      fullPath: "/projects/$projectId/queries"
      preLoaderRoute: typeof DashboardProjectsProjectIdQueriesRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    "/_dashboard/projects/$projectId/answers": {
      id: "/_dashboard/projects/$projectId/answers"
      path: "/answers"
      fullPath: "/projects/$projectId/answers"
      preLoaderRoute: typeof DashboardProjectsProjectIdAnswersRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    "/_dashboard/admin/ai-usage/$tenantId": {
      id: "/_dashboard/admin/ai-usage/$tenantId"
      path: "/$tenantId"
      fullPath: "/admin/ai-usage/$tenantId"
      preLoaderRoute: typeof DashboardAdminAiUsageTenantIdRouteImport
      parentRoute: typeof DashboardAdminAiUsageRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCompleteSignupRoute: typeof AuthCompleteSignupRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCompleteSignupRoute: AuthCompleteSignupRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdAnswersRoute: typeof DashboardProjectsProjectIdAnswersRoute
  DashboardProjectsProjectIdQueriesRoute: typeof DashboardProjectsProjectIdQueriesRoute
  DashboardProjectsProjectIdRunsRoute: typeof DashboardProjectsProjectIdRunsRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdAnswersRoute:
      DashboardProjectsProjectIdAnswersRoute,
    DashboardProjectsProjectIdQueriesRoute:
      DashboardProjectsProjectIdQueriesRoute,
    DashboardProjectsProjectIdRunsRoute: DashboardProjectsProjectIdRunsRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardReportsRouteChildren {
  DashboardReportsReportIdRoute: typeof DashboardReportsReportIdRoute
}

const DashboardReportsRouteChildren: DashboardReportsRouteChildren = {
  DashboardReportsReportIdRoute: DashboardReportsReportIdRoute,
}

const DashboardReportsRouteWithChildren =
  DashboardReportsRoute._addFileChildren(DashboardReportsRouteChildren)

interface DashboardAdminAiUsageRouteChildren {
  DashboardAdminAiUsageTenantIdRoute: typeof DashboardAdminAiUsageTenantIdRoute
}

const DashboardAdminAiUsageRouteChildren: DashboardAdminAiUsageRouteChildren = {
  DashboardAdminAiUsageTenantIdRoute: DashboardAdminAiUsageTenantIdRoute,
}

const DashboardAdminAiUsageRouteWithChildren =
  DashboardAdminAiUsageRoute._addFileChildren(
    DashboardAdminAiUsageRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardReportsRoute: typeof DashboardReportsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVisibilityRoute: typeof DashboardVisibilityRoute
  DashboardWidgetsRoute: typeof DashboardWidgetsRoute
  DashboardAdminAiKeysRoute: typeof DashboardAdminAiKeysRoute
  DashboardAdminAiUsageRoute: typeof DashboardAdminAiUsageRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsProjectIdKnowledgeRoute: typeof DashboardProjectsProjectIdKnowledgeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContentRoute: DashboardContentRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardReportsRoute: DashboardReportsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVisibilityRoute: DashboardVisibilityRoute,
  DashboardWidgetsRoute: DashboardWidgetsRoute,
  DashboardAdminAiKeysRoute: DashboardAdminAiKeysRoute,
  DashboardAdminAiUsageRoute: DashboardAdminAiUsageRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsProjectIdKnowledgeRoute:
    DashboardProjectsProjectIdKnowledgeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FunnelRouteChildren {
  FunnelNewProjectRoute: typeof FunnelNewProjectRoute
}

const FunnelRouteChildren: FunnelRouteChildren = {
  FunnelNewProjectRoute: FunnelNewProjectRoute,
}

const FunnelRouteWithChildren =
  FunnelRoute._addFileChildren(FunnelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FunnelRoute: FunnelRouteWithChildren,
  EmbedEmbedTokenRoute: EmbedEmbedTokenRoute,
  SharedReportsShareTokenRoute: SharedReportsShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
